apps/coord/views.py
import pymysql
from flask import Blueprint, render_template, request
from flask.wrappers import Response
from flask_pydantic import validate
from slugify import slugify
from werkzeug.datastructures import Headers

from config import config

from .constants import ExtEnum
from .serializers import FormatSettings, Point, Query
from .track_file import makegpx, makejson, makekml

coord_bp = Blueprint("coord", __name__)

FORMATS = (
    {"ext": ExtEnum.GPX, "label": "GPX"},
    {"ext": ExtEnum.KML, "label": "KML"},
    {"ext": ExtEnum.GEOJSON, "label": "GeoJSON"},
    {"ext": ExtEnum.MAP, "label": "На карте"},
)

FORMAT_SETTINGS = {
    ExtEnum.KML: FormatSettings(makekml, "kml", "application/vnd.google-earth.kml+xml"),
    ExtEnum.GPX: FormatSettings(makegpx, "gpx", "application/gpx+xml"),
    ExtEnum.GEOJSON: FormatSettings(makejson, "geojson", "application/vnd.geo+json"),
}


def get_project(project: str):
    lang, pr = project.split("wiki")
    if not pr:
        pr = "pedia"
    return f"{lang}.wiki{pr}.org"


@coord_bp.route("/")
@validate(query=Query)
def index_coord():
    query_params: Query = request.query_params

    if not query_params.category:
        return render_template(
            "coord.html", form=query_params.dict(), formats=FORMATS, regions={}
        )

    connection = pymysql.Connect(
        host=config.DB_REPLICA_HOST,
        port=config.DB_PORT,
        user=config.DB_USER,
        password=config.DB_PASS,
        database=f"{query_params.wiki}_p",
    )

    with connection:
        with connection.cursor() as cursor:
            sql = """SELECT `page`.`page_title`,
                            `geo_tags`.`gt_name`,
                            `geo_tags`.`gt_primary`,
                            `geo_tags`.`gt_lat`,
                            `geo_tags`.`gt_lon`
                    FROM `geo_tags`
                    JOIN `page` ON `geo_tags`.`gt_page_id` = `page`.`page_id`
                    WHERE `gt_page_id` IN
                        (SELECT `cl_from`
                         FROM `categorylinks`
                         WHERE `cl_to` = %s)
                      AND `page_namespace` = 0
                      AND `gt_globe` = "earth"
                      {};
                      """.format(
                "" if query_params.not_primary else "AND `gt_primary` = 1"
            )
            cursor.execute(sql, (query_params.category.replace(" ", "_"),))
            points = [Point(*el) for el in cursor.fetchall()]

    if query_params.ext == ExtEnum.MAP or not points:
        return render_template(
            "coord.html",
            form=query_params.dict(),
            formats=FORMATS,
            points=makejson(points, query_params.category),
            project=get_project(query_params.wiki),
        )

    elif query_params.ext in FORMAT_SETTINGS.keys():
        filename = slugify(query_params.category)
        headers = Headers()
        headers.add(
            "Content-Disposition",
            "attachment",
            filename=f"{filename}.{FORMAT_SETTINGS[query_params.ext].ext}",
        )
        response = Response(
            FORMAT_SETTINGS[query_params.ext].func(
                points, query_params.category, get_project(query_params.wiki)
            ),
            headers=headers,
            content_type=FORMAT_SETTINGS[query_params.ext].content_type,
        )
    else:
        response = render_template(
            "coord.html", form=query_params.dict(), formats=FORMATS
        )

    return response

apps/gkgn/views.py
import json
from dataclasses import dataclass
from typing import Any

from flask import Blueprint, render_template, request
from sqlalchemy import select

from apps.cache import cache, make_cache_key
from apps.db import session

from .constants import LevelEnum
from .models import Object, Type

gkgn_bp = Blueprint("gkgn", __name__)


def to_int(value: Any) -> int:
    try:
        return int(value)
    except (TypeError, ValueError):
        return 0


@dataclass
class Form:
    gkgn_id: str
    name: str
    region_id: int
    district_id: int
    type_id: int

    def sa_filters(self) -> list[Any]:
        result = []

        if self.name:
            if len(self.name) > 3:
                result.append(Object.name.like(f"{self.name}%"))
            else:
                result.append(Object.name == self.name)
        if self.gkgn_id:
            result.append(Object.gkgn_id == self.gkgn_id)
        if self.region_id:
            result.append(Object.region_id == self.region_id)
        if self.district_id:
            result.append(Object.district_id == self.district_id)
        if self.type_id:
            result.append(Object.type_id == self.type_id)
        return result

    def order_by(self) -> str:
        if request.values.get("order_by") in ("gkgn_id", "name"):
            return request.values["order_by"]
        else:
            return "name"

    def cache_key(self):
        return make_cache_key(
            "gkgn",
            "gkgn_id",
            self.gkgn_id,
            "name",
            self.name,
            "region_id",
            self.region_id,
            "district_id",
            self.district_id,
            "type_id",
            self.type_id,
        )


def get_types() -> list[Any]:
    types_cache_key = make_cache_key("gkgn", "types")

    if types_raw := cache.get(types_cache_key):
        return json.loads(types_raw)

    query = select(Type.id, Type.name).order_by(Type.name)
    types = [dict(obj._mapping) for obj in session.execute(query).all()]

    cache.set(types_cache_key, json.dumps(types), ex=60 * 60 * 24)

    return types


def get_regions() -> list[Any]:
    regions_cache_key = make_cache_key("gkgn", "regions")

    if regions_raw := cache.get(regions_cache_key):
        return json.loads(regions_raw)

    query = (
        select(Object.id, Object.name)
        .where(Object.level == LevelEnum.REGION.value)
        .order_by(Object.name)
    )
    regions = [dict(obj._mapping) for obj in session.execute(query).all()]

    cache.set(regions_cache_key, json.dumps(regions), ex=60 * 60 * 24)

    return regions


def get_districts(region_id: int) -> list[Any]:
    if not region_id:
        return []

    districts_cache_key = make_cache_key("gkgn", "districts", region_id)

    if districts_raw := cache.get(districts_cache_key):
        return json.loads(districts_raw)

    query = (
        select(Object.id, Object.name)
        .where(
            Object.level == LevelEnum.DISTRICT.value,
            Object.region_id == region_id,
        )
        .order_by(Object.name)
    )
    districts = [dict(obj._mapping) for obj in session.execute(query).all()]

    cache.set(districts_cache_key, json.dumps(districts), ex=60 * 60 * 24)

    return districts


@gkgn_bp.route("/")
def index_gkgn():
    form = Form(
        gkgn_id=request.values.get("gkgn_id", "").lstrip("0"),
        name=request.values.get("name", ""),
        region_id=to_int(request.values.get("region_id")),
        district_id=to_int(request.values.get("district_id")),
        type_id=to_int(request.values.get("type_id")),
    )

    result = []
    if filters := form.sa_filters():
        query = select(Object).where(*filters).order_by(form.order_by())
        result = session.scalars(query).all()

    return render_template(
        "gkgn/index.html",
        regions=get_regions(),
        districts=get_districts(form.region_id),
        types=get_types(),
        result=result,
        len=len(result),
        form=form,
    )

apps/templates/base.html
<!DOCTYPE html>
<html lang="ru">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- Bootstrap CSS -->
  <link href="https://tools-static.wmflabs.org/cdnjs/ajax/libs/twitter-bootstrap/5.1.3/css/bootstrap.min.css"
    rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
    crossorigin="anonymous">

  {% if title %}
  <title>{{title}} - DimaBot</title>
  {% else %}
  <title>DimaBot</title>
  {% endif %}

  {% block extend_css %}{% endblock %}

</head>

<body>
  <div class="container-fluid ">
    <div class="row justify-content-center p-2">
      <div class="col col-10">
        <ul class="nav nav-tabs">
          <li class="nav-item"><a class="nav-link {% if nav_index %}active{% endif %}"
              href="{{ url_for('index') }}">Главная</a></li>
          <li class="nav-item"><a class="nav-link {% if nav_gkgn %}active{% endif %}"
              href="{{ url_for('gkgn.index_gkgn') }}">ГКГН</a></li>
          <li class="nav-item"><a class="nav-link {% if nav_coord %}active{% endif %}"
              href="{{ url_for('coord.index_coord') }}">Экспорт координат</a></li>
          <li class="nav-item"><a class="nav-link {% if nav_template_params %}active{% endif %}"
              href="{{ url_for('template_params.index') }}">Параметры шаблонов</a></li>
        </ul>
      </div>
      <div class="tab-content col col-10 mt-3">
        {% block content %}{% endblock %}
      </div>
    </div>
  </div>
  {% block extend_js %}{% endblock %}
</body>

</html>

apps/templates/coord.html
{% extends "base.html" %}

{% set nav_coord = True %}

{% block content %}
<form action="{{ url_for('coord.index_coord') }}" method="GET">
	<div class="row mb-3">
		<label for="wiki" class="col-sm-2 form-label">Проект:</label>
		<div class="col-sm-6">
			<input id="wiki" name="wiki" class="form-control" required value="{{ form.wiki }}">
		</div>
	</div>
	<div class="row mb-3">
		<label for="category" class="col-sm-2 form-label">Категория:</label>
		<div class="col-sm-6">
			<input id="category" name="category" class="form-control" required value="{{ form.category }}">
		</div>
	</div>
	<div class="row mb-3">
		<label class="col-sm-2 form-label">Опции:</label>
		<div class="col-sm-6">
			<div class="form-check form-check-inline">
				<input class="form-check-input" type="checkbox" name="not_primary" id="not_primary" {% if
					form.not_primary %}checked{% endif %}><label class="form-check-label"
					for="not_primary">Дополнительные координаты</label>
			</div>
		</div>
	</div>
	<div class="row mb-3">
		<label class="col-sm-2 form-label">Формат:</label>
		<div class="col-sm-6">
			{% for format in formats %}
			<div class="form-check form-check-inline">
				<input class="form-check-input" type="radio" name="ext" id="ext{{ loop.index }}" value="{{ format.ext.value }}" {% if form.ext==format.ext
					%}checked{% endif %}>
				<label class="form-check-label" for="ext{{ loop.index }}">{{ format.label }}</label>
			</div>{% endfor %}
		</div>
	</div>
	<div class="row mb-3">
		<div class="col-sm-2"></div>
		<div class="col-sm-6">
			<button type="submit" class="btn btn-outline-dark">Отправить</button>
		</div>
	</div>
</form>

{% if points %}
<div id="map" style="height: calc(100vh - 25rem); min-height: 500px;"></div>
{% endif %}
{% endblock %}

{% block extend_css %}
{% if points %}
<link rel="stylesheet" href="https://tools-static.wmflabs.org/cdnjs/ajax/libs/leaflet/1.9.3/leaflet.min.css" />
<link rel="stylesheet" href="https://tools-static.wmflabs.org/cdnjs/ajax/libs/leaflet.markercluster/1.5.3/MarkerCluster.min.css" />
<link rel="stylesheet" href="https://tools-static.wmflabs.org/cdnjs/ajax/libs/leaflet.markercluster/1.5.3/MarkerCluster.Default.min.css" />
<link rel="stylesheet" href="https://tools-static.wmflabs.org/cdnjs/ajax/libs/leaflet.fullscreen/2.4.0/Control.FullScreen.min.css" />
{% endif %}
{% endblock %}

{% block extend_js %}
{% if points %}
<script src="https://tools-static.wmflabs.org/cdnjs/ajax/libs/leaflet/1.9.3/leaflet.min.js"></script>
<script src="https://tools-static.wmflabs.org/cdnjs/ajax/libs/leaflet.markercluster/1.5.3/leaflet.markercluster.min.js"></script>
<script src="https://tools-static.wmflabs.org/cdnjs/ajax/libs/leaflet.fullscreen/2.4.0/Control.FullScreen.min.js"></script>

<script type="text/javascript">

	function desc_popup(feature) {
		return '<div class="text-center"><h5><b>' + feature.properties.name + '</b></h5></div> \
                      <div class="text-center"><b><a href="https://{{ project }}/wiki/' + feature.properties.title + '" target="_blank">Статья на Вики</a></b></div>'
	}

	var markerArray = [];

	var place_arr = {{ points| safe }};
	var project = '{{ project }}';

	var markers = L.markerClusterGroup({
		showCoverageOnHover: false,
		maxClusterRadius: 20
	});

	var osm_layer = L.tileLayer('https://maps.wikimedia.org/osm-intl/{z}/{x}/{y}.png', {
		attribution: 'Data: &copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors \
        	    			  Tiles: &copy; <a href="https://wikimediafoundation.org/w/index.php?title=Maps_Terms_of_Use#Where_does_the_map_data_come_from.3F">Wikimedia</a> contributors'
	});

	var map = L.map('map', {
		fullscreenControl: true,
		fullscreenControlOptions: {
			position: 'topleft'
		},
		layers: [osm_layer]
	});

	L.geoJSON(place_arr, {
		pointToLayer: function (feature, latlng) {
			var marker = L.marker(latlng).bindPopup(desc_popup(feature))
			markerArray.push(marker);
			return markers.addLayer(marker);
		}
	}).addTo(map);

	var group = L.featureGroup(markerArray);
	map.fitBounds(group.getBounds());

</script>
{% endif %}
{% endblock %}

apps/templates/index.html
{% extends "base.html" %}

{% set nav_index = True %}

{% block content %}
<h2>Привет!</h2>
<p>На этом сервере крутятся два бота - <a href="//ru.wikipedia.org/wiki/U:DimaBot">DimaBot</a> и <a
        href="//ru.wikipedia.org/wiki/U:DimaABot">DimaABot</a>. Домашней для них является википедия на русском языке, там же обитает их <a href="//ru.wikipedia.org/wiki/U:Dima st bk">хозяин</a>.
</p>
<p>Список задач обоих ботов можно найти на их страницах в РуВики.</p>
{% endblock %}